import type { Metadata } from "next";
import { Geist, Geist_Mono, Sofia_Sans_Condensed } from "next/font/google";
import "./globals.css";
import TopBanner from "./components/layout/TopBanner";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import { CartProvider } from "./Context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const sofia = Sofia_Sans_Condensed({
  weight: ['300'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={sofia.className}>
        <CartProvider>

        
        <TopBanner />
        <Navbar/>
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
